[package]
name = "adventofcode-2015"
version = "0.1.0"
authors = ["Jed Davis <jld@panix.com>"]
exclude = ["input/*"]
[[bin]]
name = "day1"
path = "src/day1.rs"
[[bin]]
name = "day2"
path = "src/day2.rs"
